### ISSUE TITLE
Customizable Redis Client

### ISSUE THREAD

**Issue by knoxcard** [socketio/socket.io-redis-adapter#314]
The package.json file states **redis** in dependencies, but then uses **ioredis** in devDependencies?

Redis client dependencies should be dropped and the Redis client should load into the library via code.

**Comment by knoxcard** [comment]
For example, this was done on this repo...connect-redis

https://github.com/tj/connect-redis/blob/master/lib/connect-redis.js

**Comment by knoxcard** [comment]
We gotta roll this out ASAP! I'll try and submit a PR as soon as possible, this is urgent!

**Comment by darrachequesne** [comment]
Totally agree with that. The following signature would indeed be better:

```js
io.adapter(redisAdapter(pubClient, subClient, options));
```

My only concern is about the existing code examples on the Internet which display the current form... Do you think this breaking change is worth it?

**Comment by darrachequesne** [comment]
For future readers, this was done in release [7.0.0](https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.0.0):

```js
const io = require('socket.io')(3000);
const { createClient } = require('redis');
const redisAdapter = require('@socket.io/redis-adapter');

const pubClient = createClient({ host: 'localhost', port: 6379 });
const subClient = pubClient.duplicate();
io.adapter(redisAdapter(pubClient, subClient));
```
