### ISSUE TITLE
Emitting to rooms not working

### ISSUE THREAD

**Issue by timB73** [socketio/socket.io-redis-adapter#373]
Hi, for some reason it looks like the rooms are not working when I use multiple dynos on Heroku. I've enabled session affinity, so assume I'm doing something wrong setting up the redis adapter. But I'm not getting any errors as far as I can tell.
I'm using version 5.3 as I haven't migrated to socket.io version 3 yet.

Here is my code:
````
const sticky = require('sticky-session');
const express = require('express');

const app = express();
app.set('trust proxy', true);
const server = require('http').createServer(app);
const SocketServer = require('socket.io');
const redisAdapter = require('socket.io-redis');
const keys = require('./config/keys');
const start = require('./server');

const io = new SocketServer(server, { perMessageDeflate: false });

const WORKERS = process.env.WEB_CONCURRENCY || 1;
const PORT = process.env.PORT || 5000;

console.log(`Running ${WORKERS} workers`);

if (!sticky.listen(server, PORT, { workers: WORKERS })) {
  // Master code
  server.once('listening', () => {
    console.log(`Server started on ${PORT} port`);
    io.adapter(redisAdapter(keys.redisURL));
  });
} else {
  // worker code
  start(app, io);
}
````
In the start function called by the worker code section I call `app.set('socketio', io)` to make the io instance available globally in my app. Then I'm using the rooms like this:
`io.to(roomId).emit(message)`

Am I doing something wrong? I appreciate any help here.
Thanks!

**Comment by mding5692** [comment]
@timB73 is it a similar issue to: https://github.com/socketio/socket.io/issues/3673, would one of those comments help?

**Comment by mding5692** [comment]
@timB73 this issue fixed it for me: https://github.com/socketio/socket.io/issues/3743, turns out i was using different types of roomIds where one type was number and the other type was string, enforcing string type of roomIds when joining and emitting fixed my problem

**Comment by darrachequesne** [comment]
@timB73 did you find a solution?

**Comment by timB73** [comment]
@darrachequesne Hi, I believe this was caused by using Node clusters / sticky-session module, rather than multiple dynos. I removed the cluster code to instead use a single process (still multiple dynos) and it worked. Not sure why.

**Comment by umutc** [comment]
Hey guys the was related with types.
For example
clientSide(angular): 
this._socketio.socket.on('connected', () => this._socketio.socket.emit('join', user_id)); // user_id must be string!
serverSide(emitter):
io.to(user_id).emit(event, JSON.stringify(payload));  // user_id must be string!

**Comment by darrachequesne** [comment]
For future readers: we have created a new adapter which works with Node.js cluster module.

Please see the documentation here: https://socket.io/docs/v4/cluster-adapter/
