### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by fliespl** [socketio/socket.io-redis-adapter#374]
Version: 6.0.1

I am curious if documentation is still valid, cause example from it fails immediately.

```
const redisAdapter = require('socket.io-redis')({'host': '127.0.0.1', 'port': 6379});

redisAdapter.pubClient.on('error', function(){});
redisAdapter.subClient.on('error', function(){});
```

```
redisAdapter.pubClient.on('error', function(){});
                       ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (E:\Workspace\web\sf5\socket\server.js:6:24)
```

**Comment by cinout** [comment]
I encountered a similar issue. Have you found a solution to this issue @fliespl ?

I used TS way to create my redisAdapter, the code snippet is here:
```
import { RedisClient } from "redis";
import { createAdapter } from "socket.io-redis";

const pubClient = new RedisClient({ host:hostName, port: portNum});
const subClient = pubClient.duplicate();

const redisAdapter = createAdapter({
      pubClient,
      subClient,
    });
```

Then if I do `console.log( redisAdapter.pubClient )`, the output is `undefined`.

**Comment by fliespl** [comment]
@cinout yes, I did it like that.

Hooked events on custom defined sub/pubClient without going through redisAdapter.pubClient.

```
const pubClient = redis.createClient(6379, '127.0.0.1');
const subClient = pubClient.duplicate();

const redisAdapter = require('socket.io-redis').createAdapter({pubClient: pubClient, subClient: subClient})

pubClient.on('error', (err) => {
    console.log(err);
})
subClient.on('error', (err) => {
    console.log(err);
})
```

**Comment by cinout** [comment]
> @cinout yes, I did it like that.
> 
> Hooked events on custom defined sub/pubClient without going through redisAdapter.pubClient.
> 
> ```
> const pubClient = redis.createClient(6379, '127.0.0.1');
> const subClient = pubClient.duplicate();
> 
> const redisAdapter = require('socket.io-redis').createAdapter({pubClient: pubClient, subClient: subClient})
> 
> pubClient.on('error', (err) => {
>     console.log(err);
> })
> subClient.on('error', (err) => {
>     console.log(err);
> })
> ```

@fliespl That works. Thank you for the help!

**Comment by darrachequesne** [comment]
Arf, that is indeed a change in the latest release that wasn't updated in the documentation, sorry for that.

I think the best way for now is to provide your own redis clients, as suggested [above](https://github.com/socketio/socket.io-redis/issues/374#issuecomment-757139929).
