### ISSUE TITLE
Remote Fetch Socket

### ISSUE THREAD

**Issue by anshulnegitc** [socketio/socket.io-redis-adapter#391]
In socket v4
this line
`await io.of("/admin").in("room1").fetchSockets();`
provides socket instances of multiple node or single node ?

**Comment by darrachequesne** [comment]
With the Redis adapter, the `fetchSockets()` method will return the socket instances for all Socket.IO servers.

**Comment by anshulnegitc** [comment]
I tried with 2 Socket.IO servers but not receiving the output for fetchSockets(), and monitored the Redis server, there were no pub-sub messages.
I have applied the Redis Adapter as follows
`socketIo.adapter(redis(uri),{
    requestsTimeout: 10000
}));`
and used fetchSockets(); as
`await io.of("/admin").in("room1").fetchSockets();`
Am I missing the syntax ?

**Comment by darrachequesne** [comment]
> and it shows timeout for some(request timeout to 30sec)

Timeouts may indeed happen if a Socket.IO server does not respond to the request sent on Redis pub/sub, but it should work properly in most cases.

> And can you specify the Redis version as on the server I am running 4.0.9 and locally 5.0.7 will it affect the functionality?

We are relying on the [Redis pub/sub](https://redis.io/topics/pubsub) mechanism, which AFAIK hasn't evolved much in recent Redis releases, so I'd say no.

**Comment by anshulnegitc** [comment]
I updated to the latest version of Redis on the server still timeout persist but when I switched from the Redis server(installed on ubuntu(digital ocean)) to **Redislabs cloud** timeout wasn't happenning.
then at last I changed my namespace after that timeout doesn't come up on Redis Server(installed on ubuntu(digital ocean))
My Socket.Io server are on ELB AWS.
Can you tell why it is behaving so ?

**Comment by darrachequesne** [comment]
> Can you tell why it is behaving so ?

That's weird indeed. Did you find a solution?

**Comment by y4my4my4m** [comment]
I seem to be having the same issue @darrachequesne 

```
"socket.io": "^4.0.1",
"socket.io-redis": "^6.1.0",
```

Every other functions are working fine, **Server A** can communicate with **Server B** and join room or emit events/data with no issue but

```
const rooms = await io.of('/').adapter.allRooms();
console.log(rooms); // a Set containing all rooms (across every node)
```

and

```
const sockets = await io.in('room3').allSockets();
console.log(sockets); // a Set containing the socket ids in 'room3'
```

Return these kind of errors:
```
Error: timeout reached while waiting for allRooms response
 at Timeout._onTimeout (/usr/src/node/node_modules/socket.io-redis/dist/index.js:379:28)
 at listOnTimeout (internal/timers.js:531:17)
 at processTimers (internal/timers.js:475:7)
```

Any hint at what may cause this?

**Comment by y4my4my4m** [comment]
Ok, I figured it out.

It's apparently not related to redis version.

The error occurs when something else is using your redis instance, in my case another server which runs Socket.io v2 was running on it. Make sure only your socket server, or at least socket servers using the same v4 are using the current redis instance.

@anshulnegitc @darrachequesne

**Comment by anshulnegitc** [comment]
I shifted my Redis database(running on Aws) to RedisLabs cloud, after that it doesn't timeout.
Currently, 3 servers are using Redis.
2 socket io server(v4) and one server where I use Redis as cache works fine till now.
@y4my4my4m might be the solution will try it

**Comment by y4my4my4m** [comment]
@darrachequesne 

I figured I'd let you know something else I've discovered.
fetchSockets() does not work properly in a redis cluster if you are not using ioredis.

**Comment by darrachequesne** [comment]
@y4my4my4m yes, I think that's because the `redis` package does not support cluster, please see: https://github.com/NodeRedis/node-redis/issues/574

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by introspection3** [comment]
@darrachequesne you should open it ,maniy people come arcoss this bug

**Comment by Henrriky** [comment]
same error

**Comment by nicholaswmin** [comment]
Correlate your server restarts with the timeouts. Do they match?
We have this issue when the platform provider moves or restarts our dynos.

Thousands of socket.io clients attempt to reconnect, we do some initialisation using that mechanism (fetch all users across all rooms ,regardlress of dyno) and so it times out because of the thousand simultaneous requests.

We're building a ticket system to ameliorate that. As in trap `SIGTERM` and send a specific time delay to the client about when to reconnect to ensure orderly reconnections. 

Oh and under our load test, `ioredis` package could handle many times more than `redis`  for some reason. I don't want to post those findings now because they are disorganised.
