### ISSUE TITLE
Send a message to the room, why can you receive it if you are not in this room?

### ISSUE THREAD

**Issue by einsqing** [socketio/socket.io-redis-adapter#394]
Send a message to the room, why can you receive it if you are not in this room?

    "socket.io": "^3.1.2",
    "socket.io-client": "^3.1.2",
    "socket.io-redis": "^6.0.1",

socket.to('room42').emit('hello', "to all clients in 'room42' room except sender");

**Comment by einsqing** [comment]
This problem also occurs when using socket.io-emitter

**Comment by einsqing** [comment]
"socket.io-client": "^4.0.0",
    "socket.io-emitter": "^3.2.0",
    "socket.io-redis": "^6.1.0",

The same problem occurs in this version

**Comment by darrachequesne** [comment]
That sounds weird, are you able to reliably reproduce?

**Comment by einsqing** [comment]
The connection is the same redis, the key is the same
`
global.io = socket(server, {
    transports: ['websocket'],
    allowEIO3: true,
    perMessageDeflate: false,
    maxHttpBufferSize: 1e7
});
io.adapter(redisAdapter({ pubClient: redisPub, subClient: redisSub, key: config.redis.key }));`

`global.io = require('socket.io-emitter')(redis, {
    key: config.redis.key
});`

**Comment by darrachequesne** [comment]
Unfortunately, I'm not able to reproduce: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io-redis/394

Could you please check?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
