### ISSUE TITLE
Version 6.1.0 breaks broadcast

### ISSUE THREAD

**Issue by GuskiS** [socketio/socket.io-redis-adapter#400]
In version 6.1.0 broadcast doesn't work as expected - it emits to all sockets in room, even the one emitting:
```ts
socket.broadcast.to(rooms).emit("message", { data });
```

in 6.0.1 this works as expected - all except `socket` recieve the message.

`socket.io` version: 4.0.1

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
