### ISSUE TITLE
request-response cycle does NxN work when it could do Nx1

### ISSUE THREAD

**Issue by doodlesbykumbi** [socketio/socket.io-redis-adapter#407]
I noticed that when a request for all sockets is issued every client gets the request (expected), and every client gets the response (hmmm?). The clients getting every response means we're consuming NxN resources for something that could be done with N.

https://github.com/socketio/socket.io-redis-adapter/blob/3242d8e91baf94720df256ab422ec5c037f6a9e1/lib/index.ts#L195

This seems to be because the response channel is singular^. A path forward could be to have the request originator start listening on a channel associated with the request id then have the responses come through this temporary channel.

**Comment by doodlesbykumbi** [comment]
I've added a draft PR^ showing how the approach would work. It could certainly be made cleaner.

**Comment by doodlesbykumbi** [comment]
Ping @darrachequesne

**Comment by darrachequesne** [comment]
Implemented in https://github.com/socketio/socket.io-redis-adapter/commit/f66de114a4581b692da759015def0373c619aab7.

**Comment by dr-js** [comment]
@darrachequesne should we change the default `publishOnSpecificResponseChannel` to `true` ?

Currently this config is still `false` in v8.3.0:
https://github.com/socketio/socket.io-redis-adapter/blob/8.3.0/lib/index.ts#L132-L133

**Comment by darrachequesne** [comment]
@dr-js yes, we totally could, though that would be a breaking change.

Since this would trigger a new major release, we could even make it the default and remove the `publishOnSpecificResponseChannel` option.

**Comment by dr-js** [comment]
I would suggest a new major release, as this should reduce response count massively when using `fetchSockets()`.

And in release changelog we could tell existing user to enable the option and gain possible performance.

**Comment by dr-js** [comment]
@darrachequesne after some cluster mode testing with [`redis-cli monitor`](https://redis.io/docs/latest/commands/monitor/),
I found `namespace.serverSideEmit()` should also use `publishOnSpecificResponseChannel` to reduce response,
currently `callback` for `serverSideEmit` still broadcast to non-specific channel,
related pull request: https://github.com/socketio/socket.io-redis-adapter/pull/536
