### ISSUE TITLE
 TypeError: this.subClient.psubscribe is not a function

### ISSUE THREAD

**Issue by yudao** [socketio/socket.io-redis-adapter#411]
Hi,

We've just upgraded redis adapter and ioredis to the latest version:
```javascript
"@socket.io/redis-adapter": "^7.0.0",
"ioredis": "^4.27.6",
```

We using RedisAdapter extended: 
```javascript
module.exports = class OurOwnRedisAdapter extends RedisAdapter {
  constructor(nsp) {
    const options = Object.assign({
      pubClient,
      subClient: pubClient.duplicate(),
      requestsTimeout: 1000
    }, config.websocket.adapter);
    super(nsp, null, options);
  }
 ...
}
```
Our pubClient is created like this:
```javascript
const pubClient = new Redis(_.merge(
    {
      dropBufferSupport: true // see https://github.com/luin/ioredis/wiki/Improve-Performance#dropbuffersupport-option
    },
    config.redis,
    scopedConfig,
    options,
    reconnectOnError,
  ));
```

And now we get this error that is difficult to know why.
```javascript
 uncaughtException {
      error: TypeError: this.subClient.psubscribe is not a function
          at new RedisAdapter (/node_modules/@socket.io/redis-adapter/dist/index.js:64:24)
          at new OurOwnRedisAdapter (/lib/websocket-adapter.js:39:5)
          at Namespace._initAdapter (/node_modules/socket.io/dist/namespace.js:40:24)
          at Server.adapter (/node_modules/socket.io/dist/index.js:133:17)
          at module.exports (/lib/websocket.js:27:6)
          at Server.<anonymous> (/server.js:25:16)
          at Object.onceWrapper (events.js:421:28)
          at Server.emit (events.js:315:20)
          at emitListeningNT (net.js:1352:10)
          at processTicksAndRejections (internal/process/task_queues.js:79:21)
    }
```

**Comment by apydo** [comment]
No idea what happens here ?

**Comment by darrachequesne** [comment]
Since version [`7.0.0`](https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.0.0), the `pubClient` and `subClient` option must be passed in the list of arguments, and not in the options anymore:

```js
const pubClient = createClient({ host: "localhost", port: 6379 });
const subClient = pubClient.duplicate();

io.adapter(redisAdapter(pubClient, subClient));
```

Which in your case should give:

```js
module.exports = class OurOwnRedisAdapter extends RedisAdapter {
  constructor(nsp) {
    const subClient = pubClient.duplicate();
    const options = Object.assign({
      requestsTimeout: 1000
    }, config.websocket.adapter);
    super(nsp, pubClient, subClient, options);
  }
 ...
}
```

**Comment by Morbden** [comment]
> Hi,
> 
> We've just upgraded redis adapter and ioredis to the latest version:
> 
> ```js
> "@socket.io/redis-adapter": "^7.0.0",
> "ioredis": "^4.27.6",
> ```
> 
> We using RedisAdapter extended:
> 
> ```js
> module.exports = class OurOwnRedisAdapter extends RedisAdapter {
>   constructor(nsp) {
>     const options = Object.assign({
>       pubClient,
>       subClient: pubClient.duplicate(),
>       requestsTimeout: 1000
>     }, config.websocket.adapter);
>     super(nsp, null, options);
>   }
>  ...
> }
> ```
> 
> Our pubClient is created like this:
> 
> ```js
> const pubClient = new Redis(_.merge(
>     {
>       dropBufferSupport: true // see https://github.com/luin/ioredis/wiki/Improve-Performance#dropbuffersupport-option
>     },
>     config.redis,
>     scopedConfig,
>     options,
>     reconnectOnError,
>   ));
> ```
> 
> And now we get this error that is difficult to know why.
> 
> ```js
>  uncaughtException {
>       error: TypeError: this.subClient.psubscribe is not a function
>           at new RedisAdapter (/node_modules/@socket.io/redis-adapter/dist/index.js:64:24)
>           at new OurOwnRedisAdapter (/lib/websocket-adapter.js:39:5)
>           at Namespace._initAdapter (/node_modules/socket.io/dist/namespace.js:40:24)
>           at Server.adapter (/node_modules/socket.io/dist/index.js:133:17)
>           at module.exports (/lib/websocket.js:27:6)
>           at Server.<anonymous> (/server.js:25:16)
>           at Object.onceWrapper (events.js:421:28)
>           at Server.emit (events.js:315:20)
>           at emitListeningNT (net.js:1352:10)
>           at processTicksAndRejections (internal/process/task_queues.js:79:21)
>     }
> ```

This error happens when using 'redis' version 4.x.x, install version 3.x.x which works correctly.

**Comment by darrachequesne** [comment]
@Morbden please check https://github.com/socketio/socket.io-redis-adapter/issues/417

Please also note that `redis@4.0.0` has been released only 20 hours ago :angel:

**Comment by mr-ryan-james** [comment]
This was bad timing for some of us who weren't aware of node redis v4 being a brand new thing. I downgraded to v3 and it's working fine.
