### ISSUE TITLE
`socket.data` field sharing problem when using PM2 cluster mode

### ISSUE THREAD

**Issue by stegano** [socketio/socket.io-redis-adapter#416]
The `socket.data` field is not shared properly when using PM2 cluster mode.

This problem appears to be caused by the difference between the instance that was initially connected and the instance that handles subsequent requests due to internal load balancing of the PM2 cluster.
(In socket-io-redis-redis, it has been confirmed that each server does not store the socket object, and when a socket object is requested from the instance (or server), it is normalized and transmitted.)

It would be nice to have a function to get the data field information stored in a specific socket.

Thank you :)

**Comment by darrachequesne** [comment]
> This problem appears to be caused by the difference between the instance that was initially connected and the instance that handles subsequent requests due to internal load balancing of the PM2 cluster.

It's the same instance. Please see https://socket.io/docs/v4/using-multiple-nodes/#Sticky-load-balancing

> In socket-io-redis-adapter, it has been confirmed that each server does not store the socket object, and when a socket object is requested from the instance (or server), it is normalized and transmitted.

It is transmitted when you use the `fetchSockets()` method:

```js
// return all Socket instances
const sockets = await io.fetchSockets();

// return all Socket instances in the "room1" room of the main namespace
const sockets = await io.in("room1").fetchSockets();

// return all Socket instances in the "room1" room of the "admin" namespace
const sockets = await io.of("/admin").in("room1").fetchSockets();

// this also works with a single socket ID
const sockets = await io.in(theSocketId).fetchSockets();
```

Please see the documentation here: https://socket.io/docs/v4/server-instance/#fetchSockets

**Comment by stegano** [comment]
@darrachequesne Thanks! 😀
