### ISSUE TITLE
Emit with room id as integer is not pushing to nodes through redis adapter

### ISSUE THREAD

**Issue by dpachecorod** [socketio/socket.io-redis-adapter#418]
I had an issue with the communication between servers in a cluster using redis adapter, I was using the room ids as Integer value and somehow the sockets in the room that was in the same server receives successfully the message but the sockets in the room that where in other servers do not receive the message.

I am not completely sure but there maybe a problem with the communication through redis adapter when working with different nodes..
I solved my problem using room ids as strings.

**Comment by darrachequesne** [comment]
I could indeed reproduce, let me check.

**Comment by Amenocy** [comment]
same issue here, I added string char to the beginning of the room.

**Comment by fcqpl** [comment]
Same issue

**Comment by ReflexFox** [comment]
I have been looking for this problem for a long time,I added string char to the beginning fix it!

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/214b5d1a8d4f1bc037712ed53dceba7ee55ea643, included in version [7.0.1](https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.0.1). Sorry for that.
