### ISSUE TITLE
After upgrade socket.io to 4.2.0, get type error with redis-adapter

### ISSUE THREAD

**Issue by suhaotian** [socketio/socket.io-redis-adapter#419]
**Describe the bug**
After upgrade socket.io to 4.2.0, get type error

**To Reproduce**

Please fill the following code example:

Socket.IO server version: `4.2.0`

*Server*

```js
import { Server } from 'socket.io';
import { createAdapter } from '@socket.io/redis-adapter';
import { RedisClient } from 'redis';

const io = new Server(8080);
const pubClient = new RedisClient({ host: 'localhost', port: 6379 });
const subClient = pubClient.duplicate();

io.adapter(createAdapter(pubClient, subClient));
```

**Additional context**
![2021-08-30 at 6 26 PM](https://user-images.githubusercontent.com/6512574/131325844-de34d766-d714-48f2-9063-97fe9241dd2c.png)

Ref: https://github.com/socketio/socket.io/issues/4066

**Comment by darrachequesne** [comment]
I could indeed reproduce, let me check.

**Comment by darrachequesne** [comment]
Actually, I could not reproduce: https://github.com/socketio/socket.io-fiddle/tree/issues/socket.io-redis/419

The message in the stack trace suggests a different version of the `socket.io-adapter`, could you please run `npm ls socket.io-adapter`?

**Comment by suhaotian** [comment]
![2021-09-23 at 8 37 AM](https://user-images.githubusercontent.com/6512574/134439657-d362eb7a-b6d9-481a-9fc1-69c92a3208f9.png)

**Comment by suhaotian** [comment]
ok,  after add `^` to the socket.io and socket.io-redis-adapter, and delete lock and node_modules

**Comment by suhaotian** [comment]
I think you should just use socket.io with fastify, no need plugin. fastify plugin is messy, make project code complex, like you put everything on `window` namespace

**Comment by belay09** [comment]
bro i also face the same problem but you don't need to do fancy things simply update to latest version **_npm i @socket.io/redis-adapter@8.0.1_** at this time i write this message the latest version was 8.0.1 so try to see the update with **_npm outdated_** command to see which version is latest
