### ISSUE TITLE
Circular referencia in object

### ISSUE THREAD

**Issue by jhondavila** [socketio/socket.io-redis-adapter#421]
![image](https://user-images.githubusercontent.com/7480095/133644210-17b57f4b-c8a9-4508-ad93-42ec1316b6cb.png)

I have problem with sequelize session

![image](https://user-images.githubusercontent.com/7480095/133644551-cbb72add-9b86-473f-b04d-b978c4f69176.png)

Problem to call fetchSockets()

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/c5dce438950491b608ed8ed46369b8f120fa82e4, included in version [7.0.1](https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.0.1). Thanks for reporting the issue.
