### ISSUE TITLE
Type 'RedisAdapter' not assignable to 'Adapter'

### ISSUE THREAD

**Issue by Interpause** [socketio/socket.io-redis-adapter#422]
I'm using typescript 4.4.2. Getting this type error when trying to pass adapter created using `createAdapter()` into `io.adapter()`. Currently, I just convert the adapter to any.
![Screenshot_20210927-124758_Chrome](https://user-images.githubusercontent.com/42513874/134847106-66dfeb88-2cbd-4a85-b0d6-4b709074aec5.jpg)

**Comment by suhaotian** [comment]
https://github.com/socketio/socket.io-redis-adapter/issues/419

check this one. I think same question

**Comment by Interpause** [comment]
Ah I see. Sorry for not searching thoroughly enough before opening this issue. I'll try it when I get home, thanks.
