### ISSUE TITLE
TypeError: socket.client.writeToEngine is not a function

### ISSUE THREAD

**Issue by aintHuman** [socketio/socket.io-redis-adapter#424]
Getting the following error trying to get redis working with socketio and express.

TypeError: socket.client.writeToEngine is not a function
    at <PROJECT_DIRECTORY>/server/node_modules/@socket.io/redis-adapter/node_modules/socket.io-adapter/dist/index.js:119:31

Few others here have also flagged this, but I don't see any workaround. socket.io-redis-adapter is the latest version, 7.0.0.

My socketio instance is being created like this:

--

// Create the SocketIO Server
const express                   = require('express');
const http                         = require('http');
const sio                           = require('socket.io');
const redisAdapter          = require('@socket.io/redis-adapter');
const { createClient }      = require("redis");

.
.
.
const app                = express();
const server            = http.createServer(app);
const io                    = new sio.Server(server);
const pubClient = createClient({
            port             : [redacted], 
            host             : [redacted],
            password    : [redacted]
        });
const subClient = pubClient.duplicate()
io.adapter(redisAdapter(pubClient, subClient));

**Comment by darrachequesne** [comment]
It looks like a version mismatch. Could you please check the version of `socket.io`?

**Comment by aintHuman** [comment]
socketio version is 4.0.1

**Comment by aintHuman** [comment]
Upgrading socketio to 4.3.1 seems to have fixed the issue

**Comment by awesomelike** [comment]
@aintHuman how about downgrading the redis adapter to 6.1.1?

**Comment by awesomelike** [comment]
Anyways, I think version shouldn't be the problem, as the compatibility table says that redis adapter "6.1.x and above" should match socket.io server of "4.x".
![image](https://user-images.githubusercontent.com/33417732/140167784-35f847b1-e8db-42cb-95d8-5e5bb018c2a8.png)

**Comment by HyopeR** [comment]
Hello. I encountered this problem. 
I got rid of the problem when I updated my packages as below.

<pre>
"@socket.io/redis-adapter": "^7.2.0",
"redis": "3.1.2",
"socket.io": "4.5.1",
</pre>
