### ISSUE TITLE
What happens if Redis server is down? Doesn't it crash my application?

### ISSUE THREAD

**Issue by awesomelike** [socketio/socket.io-redis-adapter#425]
I have connected my socket.io server to Redis adapter.
I have set up retry_strategy for Redis to try reconnecting every 5 seconds.

What happens if the Redis server is down?
Does it break my socket.io functionality? Does it crash my application?
Should I take some action/handle errors to prevent the app from crashing on socket.io side?
I have already set up error handlers for subClient and pubClient.

Currently, I see that, I have these logs:
```
Error: Redis connection in broken state: connection timeout exceeded.
at RedisClient.connection_gone
at Socket.<anonymous> 
at Socket.EventEmitter.emit
```

**Comment by darrachequesne** [comment]
Hi! This is documented here: https://socket.io/docs/v4/redis-adapter/#common-questions

In short, some packets will be lost, but your application should not crash.

**Comment by s-montigny-desautels** [comment]
Hi! I think the documentation could be a littre more clear on this behavior. By default, if the redis server is down the app **will** crash.

I see that the RedisAdapter is an EventEmitter. If the Redis server is down, the adapter emit an `error` event.
However, it is documented [here](https://nodejs.org/docs/latest-v17.x/api/events.html#error-events) that:
>If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.

No one seems to be listening on that event by default.

The only way to prevent the app from crashing that I have found is with this:
```js
io.of("/").adapter.on("error", noop);

// OR
process.on("uncaughtException", noop);
```

With this, the application don't crash if the redis server is down and the socket server work as intended.

**Comment by darrachequesne** [comment]
You are right. Actually, I don't think relaying the errors of the clients is great, it was added when the library created Redis clients on its own. We should change this in the next major release.
