### ISSUE TITLE
Upgrading node-redis version to 4 and redis-adapter to 7.1.0 Failing to Create Client

### ISSUE THREAD

**Issue by djaffer** [socketio/socket.io-redis-adapter#430]
After upgrading redis version to 4 and redis-adapter to 7.1.0 I am facing the error.

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type function ([Function (anonymous)])
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:312:13)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    
    
    
    
   ```
    client.on("connect", async function () {
  console.log("Redis client connected");
  const pubClient = client.duplicate();
  await pubClient.connect();

  const subClient = client.duplicate();
  await subClient.connect();
  io.adapter(redisAdapter(pubClient, subClient));
});
```

**Comment by djaffer** [comment]
The issue was I had legacy mode in the createClient.

  constclient = redis.createClient({
    legacyMode: true,
    url: `redis://<host>:<port>`
  });

**Comment by darrachequesne** [comment]
OK, I could indeed reproduce the issue with `legacyMode` set to `true`. I'm not sure how we could fix this though, the documentation describes the behavior of the classic commands, and not the PUB/SUB ones.

@djaffer have you found something?

Reference: https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md#legacy-mode

**Comment by djaffer** [comment]
Maybe what you can do is have a legacy mode that auto connects. It is up to you but it was a pain to get this to work.
