### ISSUE TITLE
error installation @socket.io/redis-adapter

### ISSUE THREAD

**Issue by 1omercohen** [socketio/socket.io-redis-adapter#432]
![image](https://user-images.githubusercontent.com/14128432/145219576-6cdcb8fe-1657-47fb-8891-74936d633b89.png)

try to install the package with yarn and got an error.
I attached a image with a error message. did not found nothing about it.

how can I resolve it?

**Comment by user37596** [comment]
This seems to be a PowerShell issue, not an issue with this repo. Have you tried quoting the argument: `yarn add '@socket.io/redis-adapter'`?

**Comment by 1omercohen** [comment]
I try also with other command linds like bash, also with npm install and yarn add.
please do not take the picture as PowerShell issue.

**Comment by darrachequesne** [comment]
@1omercohen did you find a solution? It seems your shell tries to interpret the `@` character

It seems you already tried with quotes, I'm out of ideas...

Reference: https://classic.yarnpkg.com/lang/en/docs/cli/add/

**Comment by user37596** [comment]
> I try also with other command linds like bash, also with npm install and yarn add. please do not take the picture as PowerShell issue.

But in the picture there is a PowerShell issue. Give us a new screenshot with the quotes in place so we can see the correct error message.
