### ISSUE TITLE
node-redis 4.0.0 support

### ISSUE THREAD

**Issue by tobeycodes** [socketio/socket.io-redis-adapter#433]
I tried upgrading node-redis to 4.0.0 but the redis-adapter stopped working. it is not a huge issue as downgrading to 3.1.2 fixed it. in the meantime we could add a notice to the readme to make it clear.

**Comment by darrachequesne** [comment]
For future readers, support for `redis@4` was added in [`7.1.0`](https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.1.0).

The only difference is that you now need to call `redisClient.connect()`:

```js
const { Server } = require('socket.io');
const { createClient } = require('redis');
const { createAdapter } = require('@socket.io/redis-adapter');

const io = new Server();
const pubClient = createClient({ host: 'localhost', port: 6379 });
const subClient = pubClient.duplicate();

io.adapter(createAdapter(pubClient, subClient));

Promise.all([pubClient.connect(), subClient.connect()]).then(() => {
  io.listen(3000);
});
```

See also: https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md
