### ISSUE TITLE
Synchronous processing between 2 libraries

### ISSUE THREAD

**Issue by hoangphongdhhp** [socketio/socket.io-redis-adapter#434]
"socket.io-redis-emitter":  io.to(id).emit(eventName);
"socket.io-redis-adapte":  await io.of('/').adapter.remoteJoin('<my-id>', 'room1');

**Comment by darrachequesne** [comment]
Hi! I'm not sure to understand, could you please explain your use case?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
