### ISSUE TITLE
Redis subClient channel doesn't reconnect on error

### ISSUE THREAD

**Issue by LucidThought** [socketio/socket.io-redis-adapter#446]
(This should be marked as a Question)
I'm having trouble with the pub/sub Redis clients in my io.adapter(...);

I connect to these clients when the application starts, and they work great. I can connect new sockets and emit to those socket using the redis-emitter on other projects; but my Redis server sits behind haproxy, so the connections between my service and redis timeout on a specified interval.

When this 'error' occurs in my Redis Client the pubClient goes through its (reconnecting, connect, ready) lifecycle, but the subClient only shows that it's entering the (reconnecting, connect) hooks. This subClient never becomes ready after a network event like this. From this point on, other services that emit messages into rooms are not delivered to clients through my service. Reconnecting the client to these rooms on a new port doesn't do anything, as the server isn't subscribed to the rooms with an active connection.

It's also worth noting that after this type of connection event, the subClient just stays in the 'connect' state and doesn't try to connect again (even though connection was never re-established). I've tried to take a memory snapshot of the server after a connection event like this has happened, makes the node-debugger hang and the program crash.

Am I doing something wrong in my configuration of redis or the adapter? I've cut out the relevant pieces of my code below:

```javascript
  const io = new Server(http, {
    path: '/socket/v1/tunnel',
    serveClient: false,
    cookie: false,
    pingTimeout: 20000,
    pingInterval: 25000,
  });

  const pubClient = createClient({
    url: redisAddress,
    socket: {
      reconnectStrategy() {
        return 600;
      },
    },
  });

  const subClient = pubClient.duplicate();

  Promise.all([pubClient.connect(), subClient.connect()]).then(() => {
    io.adapter(createAdapter(pubClient, subClient));

    io.on('connect', async (socket: Socket) => {
        ...handle socket transmissions here...
    }
  }
```

**EDIT** - I'm using the following package versions: 
`"redis": "^4.0.4"`, 
`"socket.io": "^4.4.1"`, 
`"@socket.io/redis-adapter": "^7.1.0"`
and I am using typescript

**Comment by LucidThought** [comment]
This might be an error with the Redis library, and the client not reconnecting properly with the package at version 4

**Comment by darrachequesne** [comment]
@LucidThought hmm OK, thanks for the update :+1: 

Do you know if this is fixed in the latest release of `redis`?

**Comment by zarnautovic** [comment]
I had same issue on node redis 4.0.4, and I updated it to 4.1.0 and it seems that subscriber reconnect working again.
