### ISSUE TITLE
What socket data exists within redis?

### ISSUE THREAD

**Issue by y4my4my4m** [socketio/socket.io-redis-adapter#447]
I am currently storing data using `socket.data.myCustomData` and am able to retrieve the data properly between servers.
However, I'm wondering if this data is stored in redis itself?

By that I mean, 
- Server 1  -> mySocket.data
- Server 2
- Server 3

If I kill Server 1, will Server 2 and Server 3 be able to access `mySocket.data` regardless of Server 1 and it's memory/process?

**Comment by darrachequesne** [comment]
Hi! The `socket.data` is not persisted to Redis, it only exists in the memory of the 1st server.

That being said, you can totally store it in Redis and fetch it upon connection.

**Comment by y4my4my4m** [comment]
@darrachequesne By storing/fetching it in Redis do you mean I should manually do a "pub/sub" to redis? Or are there built-in function in the socket.io-redis-adapter to do so?

Feel free to close this issue after your response.
Thank you for everything :)

**Comment by darrachequesne** [comment]
You can use the `fetchSockets()` method:

```js
io.on("connection", (socket) => {
  socket.data.someAttribute = 42;
});

// then
const sockets = await io.fetchSockets();
console.log(socket.data.someAttribute); // prints 42
```

Reference: https://socket.io/docs/v4/server-socket-instance/#socketdata

This also works with a cluster of Socket.IO servers, when using the Redis adapter (or any compatible adapter).

**Comment by y4my4my4m** [comment]
I'm confused now.
Didn't you just say the data doesn't persist in redis?

If `socket.data.someattribute = 42` only exists in memory on Server1, after killing server1 wouldnt we get something like this:
```javascript
io.on("connection", (socket) => {
  socket.data.someAttribute = 42;
});

// kill Server1 where the above happened

// then from Server 2
const sockets = await io.fetchSockets();
forEach(s in sockets){
 if(s.data.someAttribute === 42) return true; // this is never triggered
}
```

I understand that you can fetchSockets and get their content, but that requires getting the in-memory data from each server, correct? 
Or do you mean that using fetchSockets will make the data persistent in redis?

**Comment by darrachequesne** [comment]
> but that requires getting the in-memory data from each server

Yes, that's right :+1: 

In your example above, if server1 gets killed, the `data` is lost. Sorry for the confusion.

**Comment by y4my4my4m** [comment]
That clears things up. 
Thank you!
