### ISSUE TITLE
 missing 'error' handler on this Redis client

### ISSUE THREAD

**Issue by John8790909** [socketio/socket.io-redis-adapter#449]
I always get this error whenever I try to run the following code 

import { Server } from "socket.io";
import { createAdapter } from "@socket.io/redis-adapter";
import { Cluster } from "ioredis";

const io = new Server();

const pubClient = new Cluster([
  {
    host: <my-host-link-1>,
    port: <my-port-1>,
  },
  {
    host: <my-host-link-2>,
    port: <my-port-2>,
  },
]);

const subClient = pubClient.duplicate();

io.adapter(createAdapter(pubClient, subClient));
io.listen(3000);

And there seems to not be any clear solution could someone help me out?

**Comment by darrachequesne** [comment]
You should be able to register an error handler on the redis client:

```js
pubClient.on("error", (err) => {
  console.log(err);
});
```

Maybe the client is not able to reach the Redis server?

**Comment by John8790909** [comment]
Perhaps it may be so I'll look into it thanks for helping out

**Comment by John8790909** [comment]
I added the error handler just for it to return an error about there not being an error handler lol                                                  
`}
          missing 'error' handler on this Redis client
           ClusterAllFailedError: Failed to refresh slots cache.
           command: { name: 'cluster', args: [Array]                                                                                                                                     }                                                                                                                             
`

**Comment by John8790909** [comment]
And this too ` ReplyError: ERR This instance has cluster support disabled `

**Comment by darrachequesne** [comment]
It sounds like your Redis cluster might not be configured properly. Could you please check?

**Comment by John8790909** [comment]
Never mind I think i figured it out I just switched from io-redis to redis and now it works just fine but thanks for your help I appreciate it!
