### ISSUE TITLE
new ioredis.Cluster in getNumSub function constructor.name is not "Cluster"

### ISSUE THREAD

**Issue by ReflexFox** [socketio/socket.io-redis-adapter#450]
"ioredis": "^5.0.4",

const { createAdapter } = require("./redis-adapter");
const redisUrlArr = [url1,url2,...]
const Redis = require("ioredis");
const pubClient = new Redis.Cluster(redisUrlArr);
const subClient = pubClient.duplicate();
const io = require("socket.io")(server, {
  transports: ["websocket"],
  adapter: createAdapter(pubClient, subClient),
  cors: {
    origin: "*",
    methods: ["GET", "POST"],
  },
});

I am using ioredis to create a cluster mode redis but i fonud redis-adapter getNumSub function 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/42571543/165202666-64fc8add-61e7-4863-b677-67075d8f12f1.png">
this.pubClient.constructor.name not "Cluster"
so in redis Cluster mode fetchSockets function only can get current server users

**Comment by ReflexFox** [comment]
#451 fix it

**Comment by ReflexFox** [comment]
#451

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/d2faa8a55a9ef206976a1ef35041d068997324f9, included in version `7.2.0`.
