### ISSUE TITLE
Redis version on heroku (already at 7 and not supporting 4) vs. NPM redis (Seems latest version is 4.x)

### ISSUE THREAD

**Issue by afahim12** [socketio/socket.io-redis-adapter#457]
Hi, wondering if I am looking at this right. It seems that heroku implements redis version 6 or 7 (and no longer supports 4 and below) but when i look at the latest node modules in npm for redis i see the latest is version 4. What gives? Thank you!

**Comment by darrachequesne** [comment]
Hi! The version of the `redis` module does not follow the one of the redis server.

Here is the compatibility table: https://github.com/redis/node-redis#supported-redis-versions
