### ISSUE TITLE
Not treating `BroadcastOptions.except` as optional in all cases

### ISSUE THREAD

**Issue by Inspiravetion** [socketio/socket.io-redis-adapter#467]
I found an [old issue](https://github.com/socketio/socket.io-redis-adapter/pull/361) that fixed this issue for `broadcast()` and other scenarios but `fetchSockets()`, `addSockets()`, `delSockets()`, and `disconnectSockets()` are still using the old pattern so the following code:

```ts
const existingSockets = await this.adapter.fetchSockets({
    rooms: new Set([user.id])
})
```

throws an error like 

```
UnhandledPromiseRejectionWarning: TypeError: opts.except is not iterable
at RedisAdapter.fetchSockets (/app/backend/node_modules/@socket.io/redis-adapter/dist/index.js:609:34)
...
```

**Comment by darrachequesne** [comment]
For future readers: `adapter.fetchSockets()` is not meant to be used directly, you should use `namespace.fetchSockets()` instead.

Please reopen if needed.
