### ISSUE TITLE
Update documentation please

### ISSUE THREAD

**Issue by tahayk** [socketio/socket.io-redis-adapter#488]
Hello everyone,
I have been using socket.io and redis-adapter for the past year and they were amazing, lately after I upgraded to the last versions,
I noticed that `remoteJoin` was removed (as noted [here](https://github.com/socketio/socket.io-redis-adapter/blob/main/CHANGELOG.md#breaking-changes)) 
but the main [readme](https://github.com/socketio/socket.io-redis-adapter#redisadapterremotejoinidstring-roomstring) is still using it.
Could you please update documentation ? 
Thank you in advance.

**Comment by darrachequesne** [comment]
Done! https://github.com/socketio/socket.io-redis-adapter/commit/2d65d0adc7596a5cd305d94b0aaba69bda9260c7

Thanks for the heads-up :+1:
