### ISSUE TITLE
io.of('/').adapter.remoteJoin  give me TypeError: io.sockets.adapter.remoteJoin is not a function

### ISSUE THREAD

**Issue by youssefnabil5** [socketio/socket.io-redis-adapter#489]
i am new in socket.io

i trying to use remoteJoin but give me error  TypeError: io.sockets.adapter.remoteJoin is not a function

my code is
 `  io.sockets.adapter.remoteJoin("RG-RmuWBWRmAHigQAAC_", "rooom",  (err)=> {//join to new room
    if(err) console.log("join room error %s", JSON.stringify(err));
    else console.log("%s join to room %s", socket.id, "1");`

**Comment by darrachequesne** [comment]
The `remoteJoin()` method was removed in latest version (https://github.com/socketio/socket.io-redis-adapter/commit/fb760d9d778ed8129543bf8321d87e4fd9cca711), you can use the `socketsJoin()` method instead:

```js
// make all Socket instances join the "room1" room
io.socketsJoin("room1");

// make all Socket instances in the "room1" room join the "room2" and "room3" rooms
io.in("room1").socketsJoin(["room2", "room3"]);

// this also works with a single socket ID
io.in(theSocketId).socketsJoin("room1");
``` 

Reference: https://socket.io/docs/v4/server-api/#serversocketsjoinrooms

**Comment by youssefnabil5** [comment]
thank you very much for your attention to my question and your helpful
answer
