### ISSUE TITLE
Support for Sharded Redis Cluster

### ISSUE THREAD

**Issue by roma-glushko** [socketio/socket.io-redis-adapter#491]
From what I can see, the redis adapter doesn't support [sharded redis cluster setup](https://redis.io/docs/manual/pubsub/).

Is there any plans to bring that missing piece on?

Sharded Redis cluster was added to address scaling issues in the existing redis cluster setup where all redis instances receive and emits messages to all peers in full mesh manner.

On the surface, it seems like the adapter will need to call slightly differently called methods: [SSUBSCRIBE](https://redis.io/commands/ssubscribe), [SUNSUBSCRIBE](https://redis.io/commands/sunsubscribe) and [SPUBLISH](https://redis.io/commands/spublish).

**Comment by MatanYemini** [comment]
@darrachequesne do you have a plan for it? If so, please share, maybe I can find time ;)

**Comment by MatanYemini** [comment]
Another question on this topic, from the code it seems that the package utilizes the shard via the namespace. There is any reason why not to do it for rooms as well ?  

Thanks!

**Comment by darrachequesne** [comment]
Support for sharded pub/sub was added in version [8.2.0](https://github.com/socketio/socket.io-redis-adapter/releases/tag/8.2.0):

```js
import { Server } from 'socket.io';
import { createClient } from 'redis';
import { createShardedAdapter } from '@socket.io/redis-adapter';

const pubClient = createClient({ host: 'localhost', port: 6379 });
const subClient = pubClient.duplicate();

await Promise.all([
  pubClient.connect(),
  subClient.connect()
]);

const io = new Server({
  adapter: createShardedAdapter(pubClient, subClient)
});

io.listen(3000);
```

@MatanYemini that's a good remark, we have added a `subscriptionMode` option to control the behavior of the adapter (which defaults to sharding by namespace and by room).

See: https://github.com/socketio/socket.io-redis-adapter/commit/d3388bf7b5b64ff6d2c25a874f4956273c8e3f58

**Comment by brock-wood** [comment]
> Support for sharded pub/sub was added in version [8.2.0](https://github.com/socketio/socket.io-redis-adapter/releases/tag/8.2.0):
> 
> ```js
> import { Server } from 'socket.io';
> import { createClient } from 'redis';
> import { createShardedAdapter } from '@socket.io/redis-adapter';
> 
> const pubClient = createClient({ host: 'localhost', port: 6379 });
> const subClient = pubClient.duplicate();
> 
> await Promise.all([
>   pubClient.connect(),
>   subClient.connect()
> ]);
> 
> const io = new Server({
>   adapter: createShardedAdapter(pubClient, subClient)
> });
> 
> io.listen(3000);
> ```
> 
> @MatanYemini that's a good remark, we have added a `subscriptionMode` option to control the behavior of the adapter (which defaults to sharding by namespace and by room).
> 
> See: [d3388bf](https://github.com/socketio/socket.io-redis-adapter/commit/d3388bf7b5b64ff6d2c25a874f4956273c8e3f58)

For anyone that is using socketio-redis-adapter and AWS elasticache redis, you'll want to ensure you are using the sharded adapter. 

```typescript
createShardedAdapter(pubClient, subClient);
```

[Redis best practices AWS](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/BestPractices.Redis.html)
