### ISSUE TITLE
This.io.sockets.adapter.pubClient.isReady becomes false and is never ready again

### ISSUE THREAD

**Issue by lcgiry** [socketio/socket.io-redis-adapter#521]
Hi,

We are using socket.io-redis-adapter to link sockets shared between several servers.
At some point after the servers restart, the pubClient in the redis adapter becomes unready, and completely blocks communication between the sockets cross servers.
All communications timeout, and the pubClient never gets ready again to communication.

We have the feeling that at some point, an incident happens in  the redis adapter and that it never tries to get the pubClient ready again.

Any idea on what could be happening ?

**Comment by darrachequesne** [comment]
Hi! Which redis package are you using? `redis`? In that case, could you please open an issue in [their repository](https://github.com/redis/node-redis), with all necessary details?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
