### ISSUE TITLE
MaxListenersExceededWarning due to SSUBSCRIBE/SUNSUBSCRIBE memory leak

### ISSUE THREAD

**Issue by RoccoC** [socketio/socket.io-redis-adapter#528]
My project utilizes the `ShardedRedisAdapter` and Redis v7 to sync state across server instances. I am using the default "dynamic" subscription mode which creates a new channel subscription for each public room.

When a room is created, the new channel subscription is created and the adapter adds a listener to the client's `smessageBuffer` EventEmitter (by way of `SSUBSCRIBE` in [/lib/util.ts](https://github.com/socketio/socket.io-redis-adapter/blob/bd32763043a2eb79a21dffd8820f20e598348adf/lib/util.ts#L71)). However, this event listener is not removed when the room is deleted, and consequently I'm encountering a `MaxListenersExceededWarning `when creating more than 8 rooms regardless of whether the rooms still exist.

I should increase the client's max listener threshold since it will not be uncommon to have >8 rooms at any given time, but it also looks like `SUNSUBSCRIBE` should be updated to remove the `smessageBuffer` listener. I'm happy to raise a PR to address this, but wanted to make sure I'm not missing something! Thanks in advance!

**Comment by RoccoC** [comment]
Raised a PR here: https://github.com/socketio/socket.io-redis-adapter/pull/529 🙏

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-redis-adapter/commit/2113e8d9eff9e13f9bbd9b603b93f42de512eb44, included in version [8.3.0](https://github.com/socketio/socket.io-redis-adapter/releases/tag/8.3.0).
