### ISSUE TITLE
Lot of "ignoring unknown request" in Debug

### ISSUE THREAD

**Issue by Valentinfe** [socketio/socket.io-redis-adapter#535]
Hello,

Thanks for your amazing work !

I'm doing some load testing with socket.io (4.6.1) and socket.io-redis-adapter (8.2.1). I'm running around 5k requests.

I'm in debug mode in order to find some errors and I get a wall of "ignoring unknown request"

![image](https://github.com/socketio/socket.io-redis-adapter/assets/152896281/91e33efc-bb20-486b-a0e8-77500854e4ad)

Is it an expected behavior or am I missing something ?

**Comment by darrachequesne** [comment]
Hi! You can set `publishOnSpecificResponseChannel` to `true`, in that case the Socket.IO servers will use a Redis channel specific to the requesting node to respond (and not publish to all nodes).

**Comment by Valentinfe** [comment]
Thanks for your quick answer !

In your point of view what are the pros/cons of both options ? We will use socket.io and this adapter on heavy load (+1000req/s) so i'm trying to find the most efficient (and safest) way to do this.

**Comment by darrachequesne** [comment]
Source:

https://github.com/socketio/socket.io-redis-adapter/blob/cdb55353f83c78cabe9788683e4dd93ac4cd50c9/lib/index.ts#L480-L486

When `publishOnSpecificResponseChannel` is set to `false` (default value), the response is sent to all nodes, but only one node is interested by the response (channel name: `this.responseChannel`).

When `publishOnSpecificResponseChannel` is set to `true`, the response is only sent to the requesting node (channel name: `${this.responseChannel}${request.uid}#`).

The latter should be the default behavior, as the filtering is done by Redis, but to maintain backward-compatibility the default value is `false`.

**Comment by Valentinfe** [comment]
Thanks for your complete answer. We improve performances by a lot.

I'll share some benchmark result between the two options.
20Vpcu, 30Ghz allocated CPU, 32Go RAM

With  publishOnSpecificResponseChannel to 'false' it takes 24Ghz on average and with it to 'true' it takes 19Ghz on average, so we have an improvement of 21%.

This tests are made with Vsphere metrics reporter and are not very precise so take it with care.

Thanks again, I close this issue.

**Comment by darrachequesne** [comment]
Awesome, thanks for the update :+1: 

I've added a note about the `publishOnSpecificResponseChannel` option here: https://socket.io/docs/v4/redis-adapter/#default-adapter
