### ISSUE TITLE
Unnecessary psubscribe Operations in  Namespaces Without Local Clients Increasing Redis Pub/Sub Channels

### ISSUE THREAD

**Issue by LokeshDaga** [socketio/socket.io-redis-adapter#537]
I am addressing a critical inefficiency in our Socket.IO implementation linked to Redis psubscribe operations, particularly affecting servers configured solely for broadcasting without any active client connections. This setup leads to a persistent increase in Redis pattern channels because punsubscribe is never called in the absence of client connections, contrary to what would be expected.

**Comment by darrachequesne** [comment]
@LokeshDaga hi! Did you find the culprit? Is there something we could fix on our end?

**Comment by LokeshDaga** [comment]
@darrachequesne  This issue we've encountered while using the Redis adapter with our Node.js cluster. This problem arises when there are no clients connected to a particular node, and that node needs to publish a message on a specific namespace.

In this scenario, the node initiates a psubscribe or subscribe action on that namespace. However, since no clients are connected to it, these subscriptions are not removed after the operation is completed. Consequently, this leads to an accumulation of pub-sub channels in the Redis instance, which can impact performance and scalability over time.
